name = "lecto-translation-bot"
main = "src/index.ts"
compatibility_date = "2024-06-12"

[env.production]
name = "lecto-translation-bot"
routes = [
  { pattern = "example.com/webhook", zone_name = "example.com" }
]

[[kv_namespaces]]
binding = "KV_STORE"
id = "YOUR_KV_NAMESPACE_ID"

[env.production.kv_namespaces]
KV_STORE = { id = "YOUR_KV_NAMESPACE_ID" }

[env.production.vars]
TELEGRAM_BOT_TOKEN = "YOUR_BOT_TOKEN"
TELEGRAM_OWNER_ID = "YOUR_OWNER_ID"
LECTO_API_KEY = "YOUR_LECTO_KEY"
