[env:heltec_wifi_lora_32]
platform = espressif32
board = heltec_wifi_lora_32
framework = arduino
lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.0
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -DLORAWAN_REGION_AU915
